### ISSUE TITLE
Follows review

### ISSUE THREAD

**Issue by ken-zhong** [ken-zhong/pxl-On#27]
Users can now follow and unfollow each other!
There's a button component that contains all its own logic for following/unfollowing. 
Profile pages either have an 'edit profile' button if its your profile, or a follow/unfollow button.
Each user has a followers/following list accessible on the profile page right underneath their profile pic.

**Comment by AM-Harris** [comment]
This looks really good. A few notes:

- [x]  When I unfollow someone, the following count on my profile doesn't update in real time. I have to click it again or I have to refresh. My guess is that you aren't updating the part of state that this count reads from.
- [x] If I create an account, I have no way to look for users to follow. The real app has some photos for suggested followers. I can also search for users to follow. You'll want to seed some photos that a new user can view on the discover or feed page so that you can demo the feature.
- [x] more seed followers and followees for the demo account

**Comment by AM-Harris** [comment]
Looks good to me!
